BEGIN;
-- Official sources reviewed 2026-10-05. Each row is a distinct application program.
-- Closed/unknown cycles remain labeled; future dates and eligibility are not invented.
CREATE TEMP TABLE expanded_catalog (
 slug text, name text, funder text, url text, summary text, eligibility text,
 notes text, min_award numeric, max_award numeric, rolling boolean, status text,
 deadline timestamptz, fee numeric, categories text[], applicants text[], country text, states text[]
) ON COMMIT DROP;
INSERT INTO expanded_catalog VALUES
('creative-capital-award','Creative Capital Award','Creative Capital','https://creative-capital.org/applicationhandbook/','Project support for new artistic work, including digital, multidisciplinary and socially engaged art.','Artists 25+ with five years of professional practice; qualifying U.S. citizenship or residency status required. Degree students are excluded. Collaboratives use a lead applicant.','The 2027 award application closed April 2, 2026 at 3 PM Eastern. A later application cycle is not announced in the reviewed handbook.',15000,50000,false,'closed','2026-04-02T15:00:00-04:00',NULL,ARRAY['Music','Visual Art','Film / Video','Theater','Dance','Writing / Literature','Photography','Technology','Community Project']::text[],ARRAY['individual','collective']::text[],'United States',ARRAY[NULL]::text[]),
('awaw-environmental-art','Anonymous Was A Woman Environmental Art Grants','New York Foundation for the Arts','https://www.nyfa.org/awards-grants/anonymous-was-a-woman-environmental-art-grants/','Support for environmental art in any discipline with free public engagement.','Women, transgender or gender-nonconforming artist leads, age 18+, with U.S. residence. Projects must already be in development. Degree students and organization-led applications are excluded.','The 2026 cycle closed April 7 at 5 PM Eastern. No next-cycle deadline is supplied.',NULL,20000,false,'closed','2026-04-07T17:00:00-04:00',NULL,ARRAY['Music','Visual Art','Film / Video','Theater','Dance','Writing / Literature','Photography','Technology','Community Project']::text[],ARRAY['individual','collective','fiscal_sponsored']::text[],'United States',ARRAY[NULL]::text[]),
('nea-grants-arts-projects','NEA Grants for Arts Projects','National Endowment for the Arts','https://www.arts.gov/grants/grants-for-arts-projects','Arts project funding across performing, literary, visual and media arts, arts education and community arts.','U.S. tax-exempt nonprofits, governments and federally recognized tribes with five years of arts programming and at least $20,000 operating expenses. A 1:1 match is required. Individuals, for-profits and fiscal sponsorship applications are excluded.','The 2026 application cycles have closed. New guidelines are anticipated in December 2026; no future deadline is inferred.',10000,100000,false,'closed',NULL,NULL,ARRAY['Music','Visual Art','Film / Video','Theater','Dance','Writing / Literature','Photography','Nonprofit','Education','Community Project']::text[],ARRAY['nonprofit','organization']::text[],'United States',ARRAY[NULL]::text[]),
('puffin-film-theater-2027','Puffin Foundation Film/Video and Theater Grants','The Puffin Foundation','https://www.puffinfoundation.org/faqs','Support for socially engaged film and theater projects addressing contemporary issues and underserved audiences.','Projects must fit the currently funded disciplines; U.S. projects are prioritized. The funder rejects AI-written proposals and AI-generated project material. Review fiscal-need and full eligibility requirements.','Request portal access by November 20, 2026; mailed forms must be postmarked by November 25. Completed proposals are due December 16, 2026 at 5 PM Eastern.',NULL,NULL,false,'open','2026-12-16T17:00:00-05:00',NULL,ARRAY['Film / Video','Theater','Community Project']::text[],ARRAY['individual','nonprofit','organization']::text[],NULL,ARRAY[NULL]::text[]),
('smith-documentary-photography','W. Eugene Smith Grant','W. Eugene Smith Memorial Fund','https://www.smithfund.org/eugene-smith-grant','Funding to start or complete a documentary photographic essay addressing the human condition.','International photographers age 18+, including collaborators. Students generally use the separate student grant. AI imagery is excluded. A $50 application fee applies; fee waivers are available.','Applications close October 12, 2026 at 11:59 PM Eastern.',NULL,30000,false,'open','2026-10-12T23:59:00-04:00',50,ARRAY['Photography']::text[],ARRAY['individual','collective']::text[],NULL,ARRAY[NULL]::text[]),
('smith-student-photography','W. Eugene Smith Student Grant','W. Eugene Smith Memorial Fund','https://www.smithfund.org/the-w-eugene-smith-grant-for-student-photographers','Support for students completing an ongoing documentary photography project.','International applicants age 18+ enrolled in a recognized institution; high school students are excluded. Student identification and work in progress are required. $10 fee; waivers available. Cannot apply for both Smith grants.','Applications close October 12, 2026 at 11:59 PM Eastern.',5000,5000,false,'open','2026-10-12T23:59:00-04:00',10,ARRAY['Photography']::text[],ARRAY['student']::text[],NULL,ARRAY[NULL]::text[]),
('nase-growth-grants','NASE Growth Grants','National Association for the Self-Employed','https://www.nase.org/become-a-member/grants-and-scholarships','Small business expansion support for equipment, marketing, hiring and other growth needs.','Paid NASE membership in good standing is required. Annual members may apply immediately; monthly members must wait 90 days.','Awards are selected quarterly. Review the member application for the current review schedule.',NULL,4000,true,'open',NULL,NULL,ARRAY['Small Business']::text[],ARRAY['business']::text[],'United States',ARRAY[NULL]::text[]),
('amber-grant','Amber Grant for Women','WomensNet','https://ambergrantsforwomen.com/get-an-amber-grant/','Monthly support for women-owned businesses, including startups.','Women age 18+ owning at least 50% of a U.S. or Canadian business, including startups. Revenue-generating nonprofits may qualify; charitable-giving organizations are excluded. A $15 fee applies; waivers available.','The published next cutoff is October 31, 2026. This source does not specify a cutoff time, so no exact timestamp is inferred.',10000,10000,false,'open','2026-10-31T23:59:00-04:00',15,ARRAY['Small Business']::text[],ARRAY['business']::text[],'United States',ARRAY[NULL]::text[]),
('nsf-seed-fund','NSF Small Business Innovation Research / Technology Transfer','National Science Foundation','https://seedfund.nsf.gov/solicitation-eligibility/','Research and development funding for high-risk technology commercialization.','U.S. small businesses with fewer than 500 employees and at least 51% qualifying U.S. ownership. R&D must occur in the U.S.; principal-investigator employment rules apply. STTR requires a research-institution partner.','Begin with the official Project Pitch process. Full-proposal timing and invitations depend on the current solicitation; no exact deadline is asserted here.',NULL,NULL,false,'unannounced',NULL,NULL,ARRAY['Small Business','Technology','Research']::text[],ARRAY['business']::text[],'United States',ARRAY[NULL]::text[]),
('usda-fmpp','USDA Farmers Market Promotion Program','USDA Agricultural Marketing Service','https://www.ams.usda.gov/services/grants/fmpp','Support for direct-to-consumer agricultural markets, including farmers markets, CSAs and agritourism.','Eligible U.S. agricultural businesses, cooperatives, nonprofits, public-benefit entities and governments. Projects must benefit the local food system. A 25% cost share is required; individuals cannot apply as individuals.','The FY2026 round closed June 5, 2026. A next-cycle deadline is not supplied.',50000,500000,false,'closed',NULL,NULL,ARRAY['Agriculture / Food','Small Business','Community Project','Nonprofit']::text[],ARRAY['business','nonprofit','organization']::text[],'United States',ARRAY[NULL]::text[]),
('usda-lfpp','USDA Local Food Promotion Program','USDA Agricultural Marketing Service','https://www.ams.usda.gov/services/grants/lfpp','Support for local food intermediaries such as food hubs, shared kitchens and food incubators.','Eligible U.S. agricultural businesses, cooperatives, nonprofits, public-benefit entities and governments. Projects must benefit the local food system. A 25% cost share is required; individuals cannot apply as individuals.','The FY2026 round closed June 5, 2026. A next-cycle deadline is not supplied.',25000,500000,false,'closed',NULL,NULL,ARRAY['Agriculture / Food','Small Business','Community Project','Nonprofit']::text[],ARRAY['business','nonprofit','organization']::text[],'United States',ARRAY[NULL]::text[]),
('sare-research-education','Northeast SARE Research and Education Grants','Northeast SARE','https://northeast.sare.org/grants/get-a-grant/research-and-education-grant-program/','Farmer education projects that improve sustainable agriculture, optionally incorporating applied research.','Project leaders must work in farming and engage Northeast farmers in project need and design. This is not general farm startup or land-purchase funding.','Proposals are due October 26, 2026 at 4 PM Eastern.',30000,250000,false,'open','2026-10-26T16:00:00-04:00',NULL,ARRAY['Agriculture / Food','Research','Education']::text[],ARRAY['individual','organization','nonprofit','researcher']::text[],'United States',ARRAY['Connecticut','Delaware','Maine','Maryland','Massachusetts','New Hampshire','New Jersey','New York','Pennsylvania','Rhode Island','Vermont','West Virginia','District of Columbia']::text[]),
('sare-novel-approaches','Northeast SARE Research for Novel Approaches','Northeast SARE','https://northeast.sare.org/grants/get-a-grant/research-for-novel-approaches/','Proof-of-concept research into new sustainable farming practices.','Projects must build on preliminary evidence and document interest and practical relevance for Northeast farmers and agricultural service providers. Review the current call''s institutional requirements.','Proposals are due October 26, 2026 at 4 PM Eastern.',30000,250000,false,'open','2026-10-26T16:00:00-04:00',NULL,ARRAY['Agriculture / Food','Research']::text[],ARRAY['organization','nonprofit','researcher']::text[],'United States',ARRAY['Connecticut','Delaware','Maine','Maryland','Massachusetts','New Hampshire','New Jersey','New York','Pennsylvania','Rhode Island','Vermont','West Virginia','District of Columbia']::text[]),
('sare-professional-development','Northeast SARE Professional Development Grants','Northeast SARE','https://northeast.sare.org/grants/get-a-grant/professional-development-grant-program/','Research-based training for professionals who advise farmers on sustainable agriculture.','Projects train agricultural service providers such as extension educators, consultants, agency staff and nonprofit staff serving Northeast farmers. Review applicant requirements in the call.','Proposals are due October 26, 2026 at 4 PM Eastern. Typical awards are $30,000–$150,000; a hard maximum is not asserted.',NULL,NULL,false,'open','2026-10-26T16:00:00-04:00',NULL,ARRAY['Agriculture / Food','Education']::text[],ARRAY['organization','nonprofit','researcher','consultant']::text[],'United States',ARRAY['Connecticut','Delaware','Maine','Maryland','Massachusetts','New Hampshire','New Jersey','New York','Pennsylvania','Rhode Island','Vermont','West Virginia','District of Columbia']::text[]),
('spencer-small-research','Spencer Small Research Grants on Education','Spencer Foundation','https://www.spencer.org/grant_types/small-research-grant','Research funding to improve understanding of education across settings.','Principal investigators need an earned doctorate and affiliation with a nonprofit or public institution that administers the grant. No direct awards to individuals. International proposals are eligible. Routine program delivery and software development without research are excluded.','Applications are currently closed. No next deadline is published on the reviewed page.',NULL,50000,false,'closed',NULL,NULL,ARRAY['Research','Education','Nonprofit']::text[],ARRAY['nonprofit','organization','researcher']::text[],NULL,ARRAY[NULL]::text[]),
('nea-foundation-learning','NEA Foundation Learning and Leadership Grants','The NEA Foundation','https://www.neafoundation.org/educator-grants-and-fellowships/learning-leadership-grants/','Professional learning and collaborative study for public educators.','Current National Education Association members working in public schools or public higher education, including education support professionals. Current foundation grantees are ineligible. Tuition is not funded.','The published application window ended September 15. Confirm the next cycle with the funder; no future deadline is inferred.',NULL,5000,false,'closed',NULL,NULL,ARRAY['Education']::text[],ARRAY['individual','collective']::text[],'United States',ARRAY[NULL]::text[]),
('otf-internet-freedom','Open Technology Fund Internet Freedom Fund','Open Technology Fund','https://www.opentech.fund/funds/internet-freedom-fund/','Technology, applied research and digital-security projects protecting internet freedom.','Individuals and for-profit or nonprofit organizations worldwide can apply, subject to U.S. sanctions restrictions. Projects must address censorship, surveillance or related internet-freedom needs.','Rolling concept notes; shortlisted applicants are invited to submit a full proposal.',10000,900000,true,'open',NULL,NULL,ARRAY['Technology','Research','Nonprofit']::text[],ARRAY['individual','organization','business','nonprofit','researcher']::text[],NULL,ARRAY[NULL]::text[]);
INSERT INTO funders(name,website_url)
SELECT DISTINCT ON (s.funder) s.funder,s.url FROM expanded_catalog s
WHERE NOT EXISTS (SELECT 1 FROM funders f WHERE f.name=s.funder) ORDER BY s.funder,s.url;
INSERT INTO opportunities(funder_id,name,slug,official_url,source_url,funding_type,summary,eligibility_notes,deadline_notes,
minimum_award,maximum_award,rolling,application_status,deadline_at,application_fee,recurring,
discovered_at,last_checked_at,verification_status)
SELECT (SELECT id FROM funders f WHERE f.name=s.funder ORDER BY id LIMIT 1),s.name,s.slug,s.url,s.url,'grant',s.summary,s.eligibility,s.notes,
s.min_award,s.max_award,s.rolling,s.status,s.deadline,s.fee,true,
'2026-10-05T18:00:00-04:00','2026-10-05T18:00:00-04:00','recently_checked'
FROM expanded_catalog s ON CONFLICT(slug) DO NOTHING;
INSERT INTO opportunity_categories SELECT o.id,unnest(s.categories)
FROM expanded_catalog s JOIN opportunities o USING(slug) ON CONFLICT DO NOTHING;
INSERT INTO opportunity_applicant_types SELECT o.id,unnest(s.applicants)
FROM expanded_catalog s JOIN opportunities o USING(slug) ON CONFLICT DO NOTHING;
INSERT INTO opportunity_geographies(opportunity_id,country,state)
SELECT o.id,s.country,st.state FROM expanded_catalog s JOIN opportunities o USING(slug)
CROSS JOIN LATERAL unnest(s.states) AS st(state)
WHERE NOT EXISTS(SELECT 1 FROM opportunity_geographies g WHERE g.opportunity_id=o.id
AND g.country IS NOT DISTINCT FROM s.country AND g.state IS NOT DISTINCT FROM st.state);
INSERT INTO opportunity_geographies(opportunity_id,country) SELECT id,'Canada' FROM opportunities o WHERE slug='amber-grant' AND NOT EXISTS(SELECT 1 FROM opportunity_geographies g WHERE g.opportunity_id=o.id AND g.country='Canada');
COMMIT;
