import {before,after,test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import pg from 'pg';import dotenv from 'dotenv';
import {saveCandidate,applicationAccess,editApplication,archiveApplication,applicationTask,listApplications} from '../src/lib/applications/store';
import {recordPage} from '../src/lib/discovery/store';
import {publishCandidate} from '../src/lib/discovery/publish';
import {moderateGrant} from '../src/lib/opportunities/moderation';
import {setSavedOpportunity} from '../src/lib/opportunities/store';
import {dashboardTasks} from '../src/lib/checklists/store';
dotenv.config({path:'.env.local',quiet:true});const db=new pg.Client({connectionString:process.env.DATABASE_URL});
const schema=`applications_test_${randomBytes(8).toString('hex')}`,owner=randomUUID(),other=randomUUID(),viewer=randomUUID();let workspace:string,grant:string,oldTask:string,source:string;
before(async()=>{await db.connect();await db.query('BEGIN');await db.query(`CREATE SCHEMA ${schema}`);await db.query(`SET LOCAL search_path TO ${schema},public`);
 for(const f of (await readdir('db/migrations')).filter(f=>f.endsWith('.sql')&&f<'010').sort())await db.query((await readFile(`db/migrations/${f}`,'utf8')).replace(/^BEGIN;\s*|^COMMIT;\s*/gm,''));
 for(const [id,email] of [[owner,'application-owner@test.example'],[other,'application-other@test.example'],[viewer,'application-viewer@test.example']])await db.query('INSERT INTO users(id,email,name) VALUES($1,$2,$2)',[id,email]);
 workspace=(await db.query("INSERT INTO workspaces(name,slug,kind,created_by) VALUES('Applications','apps','individual',$1) RETURNING id",[owner])).rows[0].id;
 await db.query("INSERT INTO workspace_members(workspace_id,user_id,role) VALUES($1,$2,'owner'),($1,$3,'viewer')",[workspace,owner,viewer]);
 const otherWorkspace=(await db.query("INSERT INTO workspaces(name,slug,kind,created_by) VALUES('Other','other-apps','individual',$1) RETURNING id",[other])).rows[0].id;
 await db.query("INSERT INTO workspace_members(workspace_id,user_id,role) VALUES($1,$2,'owner')",[otherWorkspace,other]);
 grant=(await db.query("SELECT id FROM opportunities WHERE slug='awesome-nyc'")).rows[0].id;
 await setSavedOpportunity(db,owner,grant,true);
 oldTask=(await db.query("INSERT INTO grant_tasks(workspace_id,opportunity_id,title,created_by) VALUES($1,$2,'Existing task',$3) RETURNING id",[workspace,grant,owner])).rows[0].id;
 await db.query((await readFile('db/migrations/010_applications.sql','utf8')).replace(/^BEGIN;\s*|^COMMIT;\s*/gm,''));
 await db.query((await readFile('db/migrations/011_beta_access.sql','utf8')).replace(/^BEGIN;\s*|^COMMIT;\s*/gm,''));
 await db.query(await readFile('db/migrations/012_catalog_monitoring.sql','utf8'));
 await db.query((await readFile('db/migrations/014_search_discovery.sql','utf8')).replace(/^BEGIN;\s*|^COMMIT;\s*/gm,''));
 await db.query((await readFile('db/migrations/018_program_reconciliation.sql','utf8')).replace(/^BEGIN;\s*|^COMMIT;\s*/gm,''));
 await db.query((await readFile('db/migrations/019_reconciliation_alias_normalization.sql','utf8')).replace(/^BEGIN;\s*|^COMMIT;\s*/gm,''));
 await db.query((await readFile('db/migrations/020_autonomous_cataloger.sql','utf8')).replace(/^BEGIN;\s*|^COMMIT;\s*/gm,''));
 await db.query('UPDATE users SET beta_active=true,email_verified_at=now(),catalog_editor=true WHERE id=$1',[owner]);
 source=(await db.query("INSERT INTO crawl_sources(name,url,approved_domains) VALUES('Applications source','https://application.example.org',ARRAY['application.example.org']) RETURNING id")).rows[0].id;
});
after(async()=>{await db.query('ROLLBACK');await db.end();});
const input={stage:'preparing',notes:'Private application note',target_date:'2026-12-01',submitted_date:null,requested_amount:'1500',awarded_amount:''};
async function candidate(path:string,title:string){await recordPage(db,source,{url:`https://application.example.org/${path}`,title,text:'Funding applications support this program. Eligibility is on the source.',links:[],kind:'html',extracted:{}});return (await db.query('SELECT id FROM crawl_candidates WHERE source_id=$1 AND url=$2',[source,`https://application.example.org/${path}`])).rows[0].id;}
test('migration backfills existing saves and attaches original tasks without copying',async()=>{const rows=await listApplications(db,owner);assert.equal(rows.length,1);assert.equal(rows[0].stage,'saved');assert.equal(rows[0].tasks,1);assert.equal((await db.query('SELECT application_id FROM grant_tasks WHERE id=$1',[oldTask])).rows[0].application_id,rows[0].id);await setSavedOpportunity(db,owner,grant,false);await setSavedOpportunity(db,owner,grant,true);assert.equal((await listApplications(db,owner)).length,1);});
test('free users save ambiguous candidates privately, deduplicate, and enforce workspace boundaries',async()=>{
 const c=await candidate('directory','Application grant directory');const app=await saveCandidate(db,owner,c);assert.equal(await saveCandidate(db,owner,c),app);
 assert.equal((await db.query('SELECT status FROM crawl_candidates WHERE id=$1',[c])).rows[0].status,'pending');assert.equal((await applicationAccess(db,owner,app)).opportunity_id,null);
 await applicationTask(db,owner,app,'add',null,{title:'Read requirements',notes:'My note',due_date:'2026-12-01'});
 await editApplication(db,owner,app,input);assert.equal((await applicationAccess(db,owner,app)).requested_amount,'1500.00');
 await assert.rejects(()=>applicationAccess(db,other,app),/not found/);await assert.rejects(()=>editApplication(db,viewer,app,input),/denied/);await assert.rejects(()=>saveCandidate(db,viewer,c),/denied/);
 await assert.rejects(()=>editApplication(db,owner,app,{...input,target_date:'2026-02-30'}));await assert.rejects(()=>editApplication(db,owner,app,{...input,requested_amount:'-1'}));
 const task=(await db.query('SELECT id FROM grant_tasks WHERE application_id=$1',[app])).rows[0].id;
 await assert.rejects(()=>applicationTask(db,other,app,'complete',task,{}),/not found/);
 await applicationTask(db,owner,app,'complete',task,{});assert.equal((await listApplications(db,owner,{q:'directory'}))[0].completed,1);
 await archiveApplication(db,owner,app,true);assert.equal((await listApplications(db,owner,{q:'directory'})).length,0);assert.equal((await listApplications(db,owner,{q:'directory',archived:'1'})).length,1);
 await archiveApplication(db,owner,app,false);await editApplication(db,owner,app,{...input,stage:'submitted',submitted_date:'2026-11-01'});assert.equal((await listApplications(db,owner,{stage:'submitted'})).length,1);
 await applicationTask(db,owner,app,'reopen',task,{});assert.ok((await dashboardTasks(db,owner)).some(t=>t.id===task));
 await editApplication(db,owner,app,{...input,stage:'awarded',awarded_amount:'500'});assert.ok(!(await dashboardTasks(db,owner)).some(t=>t.id===task));assert.ok(!(await listApplications(db,owner,{active:true})).some(a=>a.id===app));
 assert.ok((await db.query('SELECT count(*)::int AS n FROM application_history WHERE application_id=$1',[app])).rows[0].n>=6);
});
test('publication and merging retain application IDs, notes, tasks and histories',async()=>{
 const c=await candidate('arts','Private continuity Arts Grant');const app=await saveCandidate(db,owner,c);await editApplication(db,owner,app,input);await applicationTask(db,owner,app,'add',null,{title:'Continuity task'});
 const published=await publishCandidate(db,c);assert.equal(published.outcome,'published');assert.equal((await applicationAccess(db,owner,app)).opportunity_id,published.opportunityId);
 const task=(await db.query('SELECT id,opportunity_id FROM grant_tasks WHERE application_id=$1',[app])).rows[0];assert.equal(task.opportunity_id,published.opportunityId);
 const targetApp=(await db.query('SELECT id FROM applications WHERE opportunity_id=$1 AND workspace_id=$2',[grant,workspace])).rows[0].id;
 await moderateGrant(db,owner,published.opportunityId!,'merge',grant,'application-owner@test.example');
 assert.equal((await applicationAccess(db,owner,app)).notes,input.notes);assert.equal((await applicationAccess(db,owner,app)).opportunity_id,grant);assert.equal((await applicationAccess(db,owner,targetApp)).opportunity_id,grant);
 assert.equal((await db.query('SELECT application_id FROM grant_tasks WHERE id=$1',[task.id])).rows[0].application_id,app);
 assert.equal((await db.query('SELECT application_id FROM grant_tasks WHERE id=$1',[oldTask])).rows[0].application_id,targetApp);
 assert.ok((await db.query('SELECT count(*)::int AS n FROM application_history WHERE application_id=$1',[app])).rows[0].n>=2);
});

test('merging a sole saved application does not create a second tracking record',async()=>{
 const c=await candidate('single','Sole saved continuity grant');const pub=await publishCandidate(db,c);await setSavedOpportunity(db,owner,pub.opportunityId!,true);
 const before=(await db.query('SELECT count(*)::int AS n FROM applications WHERE workspace_id=$1',[workspace])).rows[0].n;
 const id=(await db.query('SELECT id FROM applications WHERE opportunity_id=$1 AND workspace_id=$2',[pub.opportunityId,workspace])).rows[0].id;
 const target=(await db.query("SELECT id FROM opportunities WHERE name='FCA Emergency Grants'")).rows[0].id;
 await moderateGrant(db,owner,pub.opportunityId!,'merge',target,'application-owner@test.example');
 assert.equal((await applicationAccess(db,owner,id)).opportunity_id,target);
 assert.equal((await db.query('SELECT count(*)::int AS n FROM applications WHERE workspace_id=$1',[workspace])).rows[0].n,before);
});

test('worker merge preserves both private applications, notes, tasks and histories',async()=>{
 const c=await candidate('worker-merge','Worker continuity grant');const pub=await publishCandidate(db,c);await setSavedOpportunity(db,owner,pub.opportunityId!,true);
 const app=(await db.query('SELECT id FROM applications WHERE opportunity_id=$1 AND workspace_id=$2',[pub.opportunityId,workspace])).rows[0].id;
 await editApplication(db,owner,app,input);await applicationTask(db,owner,app,'add',null,{title:'Preserved worker merge task'});
 const before=(await db.query('SELECT count(*)::int n FROM applications')).rows[0].n;
 const history=(await db.query('SELECT count(*)::int n FROM application_history WHERE application_id=$1',[app])).rows[0].n;
 await db.query("INSERT INTO program_evidence_pages(opportunity_id,url,role,association,fetched_at) VALUES($1,'https://application.example.org/worker-merge','application','official-program-subpage',now())",[grant]);
 await db.query("UPDATE opportunities SET source_url=source_url||'/' WHERE id=$1",[pub.opportunityId]);
 await db.query('SELECT merge_reconciled_program($1,$2)',[pub.opportunityId,grant]);
 assert.equal((await applicationAccess(db,owner,app)).notes,input.notes);
 assert.equal((await applicationAccess(db,owner,app)).opportunity_id,grant);
 assert.equal((await db.query('SELECT count(*)::int n FROM applications')).rows[0].n,before);
 assert.equal((await db.query('SELECT count(*)::int n FROM application_history WHERE application_id=$1',[app])).rows[0].n,history);
 assert.equal((await db.query('SELECT opportunity_id FROM grant_tasks WHERE application_id=$1',[app])).rows[0].opportunity_id,grant);
});
