import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import pg from 'pg';
import dotenv from 'dotenv';
import {pageRole,programFacts,resolveProgramFacts,publisherIdentity,relatedPage} from '../src/lib/discovery/program-evidence';
import {availabilityLabel} from '../src/lib/opportunities/availability';
import {checkHours} from '../src/lib/discovery/maintenance';
import {recordPage} from '../src/lib/discovery/store';
import {publishCandidate} from '../src/lib/discovery/publish';
import {getOpportunity,parseFilters,searchCandidates,searchOpportunities,setSavedOpportunity} from '../src/lib/opportunities/store';
import {attachEvidence,applyProgramEvidence} from '../src/lib/discovery/program-store';
import {queueParserReconciliation} from '../src/lib/discovery/reconcile';
import {unifiedSearch} from '../src/lib/opportunities/results';
dotenv.config({path:'.env.local',quiet:true});
const now=new Date('2026-10-08T12:00:00Z');
const page=(url:string,title:string,text:string)=>({url,title,text,links:[],extracted:{},kind:'html' as const});
test('recurrence requires explicit evidence; opening dates never establish present acceptance',()=>{
 assert.equal(pageRole('Grants for Arts Projects','https://www.arts.gov/grants/grants-for-arts-projects','Funding supports applications from eligible organizations.'),'program');
 assert.equal(pageRole('10 grants for artists','https://example.org/roundup','Funding supports applications.'),'directory');
 const extract=(text:string)=>resolveProgramFacts(programFacts(page('https://example.org/art','Creative Grant',text),now.toISOString(),now),now);
 assert.equal(extract('This grant supports artists. This grant is offered annually.').values.recurrence,'annual');
 assert.equal(extract('This grant supports artists. This program runs quarterly.').values.recurrence,'recurring');
 assert.equal(extract('This grant supports artists. Read our annual report.').values.recurrence,undefined);
 assert.equal(extract('This grant supports artists. Previously this grant was awarded annually.').values.recurrence,undefined);
 assert.equal(extract('This grant supports artists. It is not true that this grant is offered annually.').values.recurrence,undefined);
 const opening=extract('This grant supports artists. Applications open November 1, 2026.');
 assert.equal(opening.values.opens,'2026-11-01');assert.notEqual(opening.values.status,'open');
 assert.equal(availabilityLabel('between_rounds'),'Between rounds — next dates unannounced');
 assert.equal(availabilityLabel('open',true),'Rolling applications');
 assert.equal(checkHours('closed',null,now,null,'annual'),24);
 assert.equal(checkHours('closed',null,now,new Date('2026-11-01'),null),6);
});
test('publisher identifiers deduplicate aliases without merging different programs or publishers',()=>{
 assert.equal(publisherIdentity('https://www.nyfa.org/opportunities/opportunity-info/?id=abc&utm_source=test'),publisherIdentity('https://nyfa.org/opportunities/opportunity-info?id=abc'));
 assert.notEqual(publisherIdentity('https://nyfa.org/opportunities/opportunity-info?id=abc'),publisherIdentity('https://nyfa.org/opportunities/opportunity-info?id=def'));
 assert.equal(relatedPage({name:'Creative Grant',source_url:'https://example.org/art'},page('https://www.example.org/art/faq','FAQ','Creative Grant requirements')),'official-program-subpage');
 assert.equal(relatedPage({name:'Creative Grant',source_url:'https://example.org/art'},page('https://other.example/art','Creative Grant','Funding supports artists')),null);
});
test('recurring availability, round evidence, publication deduplication and private saves survive repeated processing',async()=>{
 assert.ok(['localhost','127.0.0.1','[::1]'].includes(new URL(process.env.DATABASE_URL!).hostname),'Tests require a local database');
 const db=new pg.Client({connectionString:process.env.DATABASE_URL}),schema='availability_'+randomBytes(8).toString('hex');await db.connect();
 try{
  await db.query(`CREATE SCHEMA ${schema}`);await db.query(`SET search_path TO ${schema},public`);
  for(const f of (await readdir('db/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.query((await readFile('db/migrations/'+f,'utf8')).replace(/^BEGIN;\s*|^COMMIT;\s*/gm,''));
  await db.query("UPDATE opportunities SET publication_state='hidden'");await db.query('UPDATE crawl_sources SET enabled=false');
  const user=(await db.query("INSERT INTO users(email,beta_active) VALUES('rounds@example.invalid',true) RETURNING id")).rows[0].id;
  const workspace=(await db.query("INSERT INTO workspaces(name,slug,kind,created_by) VALUES('Rounds','rounds','individual',$1) RETURNING id",[user])).rows[0].id;
  await db.query("INSERT INTO workspace_members(workspace_id,user_id,role) VALUES($1,$2,'owner')",[workspace,user]);
  const url='https://example.org/creative';
  const source=(await db.query("INSERT INTO crawl_sources(name,url,approved_domains) VALUES('Official',$1,ARRAY['example.org']) RETURNING id",[url])).rows[0].id;
  const id=(await db.query("INSERT INTO opportunities(name,slug,source_url,official_url,funding_type,publication_origin,application_status,deadline_at,recurrence) VALUES('Creative Practice Grant','creative',$1,$1,'grant','crawler','closed','2020-01-01','annual') RETURNING id",[url])).rows[0].id;
  let o=(await getOpportunity(db,user,'creative')).opportunity;
  assert.equal(o.status,'between_rounds');assert.equal(o.current_deadline,null);assert.ok(o.previous_deadline);
  assert.equal((await searchOpportunities(db,user,parseFilters({status:'open'}))).total,0);
  assert.equal((await searchOpportunities(db,user,parseFilters({status:'between_rounds'}))).total,1);
  await setSavedOpportunity(db,user,id,true);
  const app=(await db.query('SELECT id FROM applications WHERE workspace_id=$1 AND opportunity_id=$2',[workspace,id])).rows[0].id;
  await db.query("UPDATE applications SET notes='Keep this private progress',stage='preparing' WHERE id=$1",[app]);
  await db.query("UPDATE opportunities SET recurrence=NULL WHERE id=$1",[id]);assert.equal((await getOpportunity(db,user,'creative')).opportunity.status,'round_ended');
  await db.query("UPDATE opportunities SET opens_at='2020-01-01',deadline_at=NULL,application_status='upcoming' WHERE id=$1",[id]);assert.equal((await getOpportunity(db,user,'creative')).opportunity.status,'unknown');
  const record=async(p:ReturnType<typeof page>)=>{
   await recordPage(db,source,p);
   const snapshot=(await db.query('SELECT * FROM crawl_snapshots WHERE url=$1 ORDER BY fetched_at DESC LIMIT 1',[p.url])).rows[0];
   await attachEvidence(db,id,p,snapshot,p.url===url?'program-page':'official-program-subpage');await applyProgramEvidence(db,id);return snapshot;
  };
  const first=page(url,'Creative Practice Grant','This grant supports artists. This grant is offered annually. Deadline: December 15, 2098.');
  await record(first);await record(first);
  assert.equal((await db.query('SELECT count(*)::int AS n FROM program_round_evidence WHERE opportunity_id=$1',[id])).rows[0].n,1);
  await record(page(url,'Creative Practice Grant','This grant supports artists. This grant is offered annually. Applications open November 1, 2099. Deadline: December 15, 2099.'));
  o=(await getOpportunity(db,user,'creative')).opportunity;assert.equal(o.status,'upcoming');assert.equal(o.recurrence,'annual');
  assert.equal((await db.query('SELECT count(*)::int AS n FROM program_round_evidence WHERE opportunity_id=$1',[id])).rows[0].n,2);
  await record(page(url+'/faq','FAQ','Creative Practice Grant requirements.'));
  assert.equal(new Date((await db.query('SELECT deadline_at FROM opportunities WHERE id=$1',[id])).rows[0].deadline_at).getUTCFullYear(),2099);
  const application=page(url+'/application','Application','Creative Practice Grant. Applications are open.');await recordPage(db,source,application);
  const candidate=(await db.query('SELECT id FROM crawl_candidates WHERE url=$1 ORDER BY created_at DESC LIMIT 1',[application.url])).rows[0];
  // recordPage may leave supporting pages to enrichment; insert a pending lead to exercise the publication boundary.
  const sn=(await db.query('SELECT * FROM crawl_snapshots WHERE url=$1',[application.url])).rows[0];
  const cid=candidate?.id??(await db.query("INSERT INTO crawl_candidates(source_id,url,title,kind,hash,snapshot_id,evidence,proposed) VALUES($1,$2,'Application','new',$3,$4,$5,'{}') RETURNING id",[source,application.url,sn.hash,sn.id,application.text])).rows[0].id;
  const outcome=await publishCandidate(db,cid);assert.equal(outcome.outcome,'updated');assert.equal(outcome.opportunityId,id);
  assert.equal((await db.query("SELECT count(*)::int AS n FROM opportunities WHERE publication_state='published'")).rows[0].n,1);
  await db.query("UPDATE crawl_candidates SET status='pending' WHERE id=$1",[cid]);
  assert.equal((await searchCandidates(db,user,parseFilters({q:'Application',resultType:'all'}))).total,0);
  assert.equal((await unifiedSearch(db,user,{})).total,1);
  await db.query('UPDATE catalog_automation SET paused=true');assert.equal(await queueParserReconciliation(db),undefined);
  await db.query('UPDATE catalog_automation SET paused=false');
  const duplicate=(await db.query("INSERT INTO opportunities(name,slug,source_url,official_url,funding_type,publication_origin,verification_status,last_verified_at) VALUES('Creative Practice Grant','creative-reviewed','https://www.example.org/creative','https://www.example.org/creative','grant','crawler','verified',now()) RETURNING id")).rows[0].id;
  const grouped=await unifiedSearch(db,user,{});assert.equal(grouped.total,1);assert.equal(grouped.rows[0].id,duplicate);
  const cleanup=await queueParserReconciliation(db);assert.ok(cleanup);assert.equal(await queueParserReconciliation(db),undefined);
  assert.equal((await db.query('SELECT count(*)::int AS n FROM catalog_reconciliation_runs')).rows[0].n,1);
  assert.equal((await db.query('SELECT notes,stage FROM applications WHERE id=$1',[app])).rows[0].notes,'Keep this private progress');
  assert.equal((await db.query('SELECT count(*)::int AS n FROM saved_opportunities WHERE workspace_id=$1',[workspace])).rows[0].n,1);
 }finally{await db.query('ROLLBACK');await db.query(`DROP SCHEMA ${schema} CASCADE`);await db.end();}
});
