import {requireWorkspace} from '@/lib/auth/workspace';import {pool} from '@/lib/db/pool';import {requireBetaOwner} from '@/lib/beta/security';import {emailConfigured} from '@/lib/beta/email';import {betaAdminAction} from '@/app/actions/beta';import {notFound} from 'next/navigation';
export default async function BetaAdmin({searchParams}:{searchParams:Promise<{error?:string;updated?:string}>}){const {session}=await requireWorkspace();try{await requireBetaOwner(pool,session.user.id);}catch{notFound();}const p=await searchParams;
 const invites=(await pool.query("SELECT id,email,purpose,expires_at,used_at,revoked_at FROM beta_tokens WHERE purpose IN ('invite','verify') AND created_by IS NOT NULL ORDER BY created_at DESC LIMIT 100")).rows;
 const users=(await pool.query('SELECT id,email,beta_active,email_verified_at,disabled_at FROM users ORDER BY created_at DESC LIMIT 100')).rows;
 return <><h1 className="text-3xl font-semibold">Beta access</h1><p className="mt-3">Invite people by email. Invitations expire in seven days; existing-account verification expires in 24 hours.</p>{!emailConfigured()&&<p className="mt-4 rounded border p-4">Email sending is disabled. Configure a verified sender domain, APP_URL, EMAIL_FROM and Resend before sending invitations.</p>}{p.error&&<p role="alert" className="mt-4">Couldn’t complete the request. Check email configuration, limits and account status.</p>}{p.updated&&<p role="status">Request completed.</p>}
 <form action={betaAdminAction} className="my-6 flex flex-wrap gap-3"><input type="hidden" name="operation" value="invite"/><label>Invite email<input name="email" type="email" required maxLength={254} className="ml-2 rounded border p-2"/></label><button disabled={!emailConfigured()} className="rounded border px-4 py-2 disabled:opacity-50">Send invitation</button></form>
 <h2 className="mt-6 text-xl font-semibold">Invitations and verification</h2>{invites.map(i=><div key={i.id} className="mt-3 rounded border p-4"><p className="break-all">{i.email} · {i.used_at?'Used':i.revoked_at?'Revoked':new Date(i.expires_at)<new Date()?'Expired':'Pending'} · {i.purpose}</p>{!i.used_at&&!i.revoked_at&&<form action={betaAdminAction}><input type="hidden" name="id" value={i.id}/><button name="operation" value="revoke" className="mt-2 underline">Revoke link</button></form>}</div>)}
 <h2 className="mt-8 text-xl font-semibold">Accounts</h2>{users.map(u=><div key={u.id} className="mt-3 rounded border p-4"><p className="break-all">{u.email} · {u.email_verified_at?'Verified':'Unverified'} · {u.beta_active&&!u.disabled_at?'Beta enabled':'Beta disabled'}</p>{u.id!==session.user.id&&<form action={betaAdminAction}><input type="hidden" name="id" value={u.id}/><button name="operation" value={u.beta_active&&!u.disabled_at?'disable':'enable'} className="mt-2 underline">{u.beta_active&&!u.disabled_at?'Revoke beta access':'Enable beta access'}</button></form>}</div>)}</>;
}
