import { ChecklistRefresh } from "./checklist-refresh";
import { pool } from "@/lib/db/pool";
import { checklistData } from "@/lib/checklists/store";
import { generationConfigured } from "@/lib/checklists/generate";
import { checklistAction } from "@/app/actions/checklists";
import type { Opportunity } from "@/lib/opportunities/store";
const field="mt-2 w-full rounded-lg border border-black/15 bg-white p-3";
const button="rounded-lg bg-[var(--brand)] px-4 py-2 text-sm font-semibold text-white";
export async function Checklist({userId,opportunity:o,error,updated}:{userId:string;opportunity:Opportunity;error?:string;updated?:boolean}) {
 if(!o.saved)return <section id="checklist" className="mt-8 rounded-2xl border border-black/10 bg-white p-6"><h2 className="text-2xl font-semibold">Optional to-do list</h2><p className="mt-3 text-[var(--muted)]">Save this grant to create a manual checklist or request an AI draft on the paid plan.</p></section>;
 const {workspace,tasks,jobs}=await checklistData(pool,userId,o.id);const canEdit=workspace.role!=="viewer";const active=jobs.some(j=>["queued","running"].includes(j.status));
 const hidden=(operation:string)=><><input type="hidden" name="opportunityId" value={o.id}/><input type="hidden" name="slug" value={o.slug}/><input type="hidden" name="operation" value={operation}/></>;
 return <section id="checklist" className="mt-8 rounded-2xl border border-black/10 bg-white p-6">
 <div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-2xl font-semibold">Optional to-do list</h2><span className="text-sm text-[var(--muted)]">{tasks.filter(t=>!t.completed_at).length} remaining · {tasks.filter(t=>t.completed_at).length} completed</span></div>
 <p className="mt-3 text-sm text-[var(--muted)]">Your workspace’s checklist. Task dates are separate from the funder’s published deadline.</p>
 {error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm">{error}</p>}{updated && !error && <p role="status" className="mt-4 text-sm text-[var(--brand)]">Checklist updated.</p>}
 {!canEdit && <p className="mt-4 text-sm">Your workspace role allows viewing only.</p>}
 <div className="mt-6 space-y-4">{tasks.map(t=><article key={t.id} className="rounded-xl border border-black/10 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className={`font-semibold ${t.completed_at?"line-through text-[var(--muted)]":""}`}>{t.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm text-[var(--muted)]">{t.notes}</p><p className="mt-2 text-sm">{t.due_date?`Due ${t.due_date}`:"No task date set"}{t.completed_at?" · Completed":""}</p></div>{canEdit && <form action={checklistAction}>{hidden(t.completed_at?"reopen":"complete")}<input type="hidden" name="taskId" value={t.id}/><button className={button}>{t.completed_at?"Reopen":"Mark complete"}</button></form>}</div>
 {t.source_url && <details className="mt-3 text-sm"><summary className="cursor-pointer underline">Source and uncertainty</summary><a href={t.source_url} target="_blank" rel="noopener noreferrer" className="mt-2 block break-all underline">Official requirement ↗</a><blockquote className="mt-2 border-l-2 pl-3">{t.source_excerpt}</blockquote>{t.uncertainty && <p className="mt-2">{t.uncertainty}</p>}</details>}
 {canEdit && <details className="mt-4"><summary className="cursor-pointer text-sm underline">Edit task</summary><form action={checklistAction} className="mt-3 grid gap-3">{hidden("edit")}<input type="hidden" name="taskId" value={t.id}/><label className="text-sm">Task title<input name="title" defaultValue={t.title} required maxLength={200} className={field}/></label><label className="text-sm">Notes<textarea name="notes" defaultValue={t.notes} maxLength={2000} className={field}/></label><label className="text-sm">Task due date (optional)<input type="date" name="due_date" defaultValue={t.due_date??""} className={field}/></label><button className={button}>Save task</button></form><form action={checklistAction} className="mt-3">{hidden("delete")}<input type="hidden" name="taskId" value={t.id}/><button className="text-sm text-red-700 underline">Delete task</button></form></details>}
 </article>)}</div>
 {!tasks.length && <p className="mt-5 text-sm text-[var(--muted)]">No tasks yet. Add your own whenever you’re ready.</p>}
 {canEdit && <details className="mt-6 rounded-xl bg-[#f1f4ef] p-4"><summary className="cursor-pointer font-semibold">Add a task</summary><form action={checklistAction} className="mt-4 grid gap-4">{hidden("add")}<label className="text-sm">Task title<input name="title" required maxLength={200} className={field}/></label><label className="text-sm">Notes<textarea name="notes" maxLength={2000} className={field}/></label><label className="text-sm">Task due date (optional)<input name="due_date" type="date" className={field}/></label><button className={button}>Add task</button></form></details>}
 <div className="mt-8 border-t border-black/10 pt-6"><h3 className="text-lg font-semibold">AI checklist draft <span className="ml-2 text-xs text-[var(--brand)]">PAID PLAN</span></h3><p className="mt-2 text-sm text-[var(--muted)]">Read the official grant requirements and prepare a draft. Review, edit, and confirm before any tasks become active. Existing tasks are preserved.</p>
 {workspace.plan!=="paid"?<p className="mt-4 text-sm">AI generation is available on the paid plan. Manual checklists are free. Paid access is currently enabled by an administrator.</p>:!generationConfigured()?<p className="mt-4 text-sm">AI generation is not configured yet. You can add tasks manually.</p>:canEdit && <form action={checklistAction} className="mt-4">{hidden("generate")}<button className={button} disabled={active}>{active?"Preparing draft…":"Generate checklist"}</button><p className="mt-2 text-xs text-[var(--muted)]">Up to 10 requests per workspace per day.</p></form>}
 {active && <div className="mt-4 text-sm">Your draft is being prepared. <ChecklistRefresh/></div>}
 {jobs.map(job=><div key={job.id} className="mt-6 rounded-xl border border-black/10 p-4"><p className="text-sm font-semibold">Draft requested {new Date(job.created_at).toLocaleString("en-US",{timeZone:"America/New_York"})} ET · {job.status}</p>
 {job.error && <p className="mt-3 text-sm" role="status">{job.error}</p>}{job.warnings.map((w,i)=><p key={i} className="mt-2 text-sm text-amber-800">{w}</p>)}
 {job.status==="draft" && job.draft && <form action={checklistAction} className="mt-4 space-y-4">{hidden("confirm")}<input type="hidden" name="jobId" value={job.id}/>{job.draft.map((t,i)=><fieldset key={i} disabled={!canEdit} className="rounded-lg bg-[#f7f8f5] p-4"><label className="flex items-center gap-2 text-sm font-semibold"><input name="include" type="checkbox" value={i} defaultChecked/>Include this task</label><label className="mt-3 block text-sm">Task title<input name={`title_${i}`} defaultValue={t.title} maxLength={200} required className={field}/></label><label className="mt-3 block text-sm">Notes<textarea name={`notes_${i}`} defaultValue={t.notes} maxLength={2000} className={field}/></label><label className="mt-3 block text-sm">Task due date (optional)<input name={`due_${i}`} type="date" defaultValue={t.due_date??""} className={field}/></label><a href={t.source_url} target="_blank" rel="noopener noreferrer" className="mt-3 block text-sm underline">Source requirement ↗</a><blockquote className="mt-2 border-l-2 pl-3 text-sm">{t.source_excerpt}</blockquote>{t.uncertainty && <p className="mt-2 text-sm text-amber-800">{t.uncertainty}</p>}</fieldset>)}{canEdit && <button className={button}>Confirm checklist</button>}<p className="text-xs text-[var(--muted)]">Only included tasks become active. You can continue editing them after confirmation.</p></form>}
 </div>)}
 </div></section>;
}
